- package.json
Since mochajs/mocha@1430c2b, .../.bin/_mocha no longer starts with
#!/usr/bin/env node
so just executing it will result in the attempt to run it as a shell script
> Make sure that _mocha is executed via node

- test/sanitizers.js
- validator.js
Without proper escaping, this could lead to XSS in IE9.
References:
- https://html5sec.org/#102
- https://html5sec.org/#108
- https://html5sec.org/#133
The same rule is followed by lodash, as seen here: https://github.com/lodash/lodash/blob/master/lodash.src.js#L9917
> Escaping backticks in validator.escape()

- test/validators.js
- validator.js
Fixed a bug where `isBefore()` returns `null` if either of the arguments are invalid dates.
Turns out that `isAfter()` was already returning a boolean, so I just emulated that return style. Also added a few tests to show that invalid dates will return false in `isAfter()` and `isBefore()`.
> Fix #435: Convert returned comparison in isBefore() to a boolean.

- .travis.yml
- README.md
- package.json
- test/validators.js
[contextify](https://github.com/brianmcd/contextify) doesn't work with node v4+ yet: https://github.com/brianmcd/contextify/issues/180
This PR removes it in favour of the builtin `vm` module. The `vm` module doesn't do what we need it to do in older versions of node and there doesn't appear to be a way to conditionally install `contextify` based on the version of node that's installed, so not sure what the best solution is here. Either wait until contextify is fixed, or wait until everyone upgrades to node 4+.
> Fix tests in node v4+

- CHANGELOG.md
- README.md
- test/validators.js
- validator.js
Usage:
- `isLength(str, {min: 4, max: 6})`
- `isLength(str, {min: 4})`
- `isLength(str, {max: 10})`
Because:
- More consitent with `isInt({min:0, max:0})` and `isFloat({min:0, max: 0})`
- More consitent with `isCurrency(str, options)`
- Avoids confusions like #465
- Allows `isLength({max: 10})`
- Backwards compatible.
- Better readability:
- `isLength(str, 4)` reads like `(str.length == 4)`, but actually is `(str.length >= 4)`
- Before: `isLength(str, 4, 10)` what do 4 and 10 mean?
- After: `isLength(str, {min: 4, max:10})`
closes #474
> Make `isLength() / isByteLength()` accept an options object `{min, max}`

- test/validators.js
- validator.js
> Base64 validation without regular expressions

- README.md
There should be more than one alternative for XSS Sanitization
to choose from, so this adds the DOMPurify library as a further
alternative.
This also makes some changes to the sentence's structure,
so that it rolls off the tongue more easily.  :stuck_out_tongue_winking_eye:
> provide alternative lib for xss sanitization

- README.md
- src/lib/isAscii.js
- src/lib/isEmail.js
- src/lib/isInt.js
- src/lib/isMultibyte.js
- test/validators.js
I updated the `isInt()` method so it treats numeric strings with prepended zeroes as valid integers. Since the `parseInt()` function in JavaScript properly parses zero-prepended strings, it would make sense that the `isInt()` function would support it as well.
I'm curious if it might be better for the `isInt()` function to check for integer values by using `parseInt()` and checking whether it returns NaN. That way it's ensured that the `isInt()` method will always validate integers that can properly be parsed by `toInt()` (or rather, by `parseInt()` by proxy).
> Allow prepended zeroes in toInt()

- README.md
To import a subset curly braces are required in ES6.
> Fix subset importing in README.md

- src/lib/alpha.js
Adds Danish locale `da-DK` for alpha, and alphanumeric validation.
> Danish locale (da-DK)

- src/lib/isURL.js
I think that 2083 characters URL is valid.
https://support.microsoft.com/en-us/help/208427/maximum-url-length-is-2,083-characters-in-internet-explorer
> Fix "isUrl" max length

- lib/isPostalCode.js
- src/lib/isPostalCode.js
- test/exports.js
This PR exports the list of supported locales that `isPostalCode` supports so that callers can prevent the validation function from throwing by not calling it if the locale isn't supported. 
I created this PR as a proof-of-concept to address https://github.com/chriso/validator.js/issues/719 but I'm not 100% sure this is the best approach.
> Export isPostalCode locales

- README.md
I wanted to point express-validator users to here, but I found the `isLatLong` validator lacking an example of what the supported format is.
> Add format examples to isLatLong

- src/lib/isPostalCode.js
- test/validators.js
isPostalCode validation for AU locale was checking for six digits, but Australian Postal Codes are 4 digits. Added a unit test for the use case also
> isPostalCode validation for AU locale was checking for six digits instead of four

- test/validators.js
The test started failing on 2017-10-10 because the current date is after that date.
> Fix failing test for isBefore().

- src/lib/isJWT.js
- test/validators.js
Updated the regular expression for isJWT so it's conforming to the specs.
#609 contained a regular expression where the signature part was required. However, RFC 7519 states:
>    To support use cases in which the JWT content is secured by a means
>    other than a signature and/or encryption contained within the JWT
>    (such as a signature on a data structure containing the JWT), JWTs
>    MAY also be created without a signature or encryption.  An Unsecured
>    JWT is a JWS using the "alg" Header Parameter value "none" and with
>    the empty string for its JWS Signature value, as defined in the JWA
>    specification [JWA]; it is an Unsecured JWS with the JWT Claims Set
>    as its JWS Payload.
Note that the code in the PR doesn't check if "alg" is actually "none" when the signature …
> Updated isJWT so it's conforming to specs

- .babelrc
- .eslintrc.json
- build-browser.js
- package.json
- test/client-side.js
- test/exports.js
- test/sanitizers.js
- test/validators.js
- Update `babel` dependencies
- Use `.babelrc` instead of passing `presets` and `plugins` via CLI
- Fix linting errors on `build-browser` script
- Use `babel-eslint` parser for `eslint`
- Use `@babel/register` instead of `@babel/node`, use `babel` when running all tests
Should remove `babel-plugin-add-module-exports` later on.
> Upgrade to babel 7

- README.md
The (relative) link to contributors was defaulting to `/blob/master/graph/contributors` (hence 404), I made it absolute instead.
> fix(README): link to contributors

- README.md
- src/index.js
- src/lib/isOctal.js
- test/validators.js
Added a validator `isOctal(str)` to validate strings intended to be octal numbers. It is intended for general octal numbers. It also accepts the common prefix of '0c' although it is not required to have the prefix to validate.
Changes:
* `README.md` has been updated to reflect the new isOctal addition
* `src/lib/isOctal.js` source of the validator function
* `src/index.js` modified to include `isOctal`
* `test/validators.js` added test cases to test `isOctal`
> Added isOctal validator including tests and updated README.

- lib/isHexadecimal.js
- src/lib/isHexadecimal.js
- test/validators.js
* Modified isHexdecimal to allow validation of hexdecimal strings prefixed with the standard '0x'. The '0x' prefix is not required but if it does exist in the string, it is still OK.
* Updated validator.js to include a few more test cases involving the '0x' prefix
Update:
* Added '0h' prefix as a valid hexadecimal format.
> Added validation for '0x'-prefixed hex strings.

- src/lib/isHexColor.js
- test/validators.js
The [CSS Color Module Level 4 Working Draft](https://drafts.csswg.org/css-color/#colorunits) now supports 4 or 8-digit hex colors (using the last bits for alpha transparency). 
It's already supported in [every major browser but IE](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value#Browser_compatibility) and will be supported in IE soon with their imminent switch to [Chromium](https://www.techcentral.ie/microsoft-to-begin-replacing-edge-with-its-chromium-based-browser-this-week/).
> Support CSS Colors Level 4 spec

- es/lib/isPostalCode.js
- lib/isPostalCode.js
- src/lib/isPostalCode.js
- test/validators.js
I was implementing the isPostalCode and was looking for Ireland's postal code (eircode). Looking in the documentation of Ireland i found that the letter O is not used to avoid confusion with the digit 0.
> An Eircode is a seven character alpha-numeric code made up of two parts. The first part (a Routing Key) consists of three characters and defines a principal post town span of delivery. The second part (a Unique Identifier) is unique to an address and distinguishes one address from another. A typical Eircode might read A65 F4E2. To avoid confusion, we have not used the letter 'O' in Eircodes, however the number '0' (zero) may be included in the Eircode for your address.
**Old regex**
`/^[A-z]\d[\d|w]\s\w{4}$/i`
In this code the pipe `|` is literally a check on the if the `|` as a char is …
> Add better validation for EirCode IE

- README.md
- src/index.js
- src/lib/isLocale.js
- test/validators.js
- It validates different languages for different geographical location
- Closes #954
> feat(isLocale): validate isLocale

- README.md
- src/lib/isMACAddress.js
- test/validators.js
Network devices like cisco or arista switches use mac address dot notion:
`0102.0304.05ab`
This allows it to be validated.
> Allow MAC address with dots

- README.md
The `format` info was orphaned to a table cell by itself, in the wrong column. This places it in the description for `isDate` where it belongs.
> docs: fix formatting in README

- src/lib/isCurrency.js
- test/validators.js
Some of the currency symbols starts with letters. For example: 
- Brazil Real R$
- Dominican Republic Peso RD$ 
For those cases, the RegExp pattern created to validate the currency simbol is not valid: 
Generated regex: 
```
-?(\R$) ?(0|[1-9]\d*|[1-9]\d{0,2}(\,\d{3})*)?(\.(\d{2}))?
```
Expected regex:
```
-?(R\$) ?(0|[1-9]\d*|[1-9]\d{0,2}(\.\d{3})*)?(\,(\d{2}))?
```
Resolves #1292
> Fix: isCurrency symbol validator regex

- src/lib/isLatLong.js
- src/lib/isPostalCode.js
👋 My use case requires default exports to be named and relates to https://github.com/validatorjs/validator.js/issues/1264. I only found 2 in your codebase (`isLatLong` and `isPostalCode`) that didn't have names for their default exports, so I'm updating just those two in `src/lib/`
Some benefits of naming exports:
* Functions get a `name`
* Easier to debug
* You're already doing it for the rest of your functions minus these two
I have no idea why `npm run test` built all these additional files (let me know if I did something wrong and how I can fix it)
Hope this is a helpful improvement.
Thanks!
> Give names to default exports (isLatLong & isPostalCode)

- es/lib/isBase64.js
- es/lib/isJWT.js
- lib/isBase64.js
- lib/isJWT.js
- src/lib/isBase64.js
- src/lib/isJWT.js
- test/validators.js
Handles conflicts in #1277 
closes #964 and closes #962
> Modified isJWT to use urlsafe base64 (also added)

- src/lib/isSlug.js
- test/validators.js
Issue #1287 
feat(isSlug): Fixed the problem in which isSlug() was also returning `true` for slugs with spaces for e.g. `not a-slug`.
I created a regex which will reject the slug while testing if it has spaces in the beginning, in the middle or at the end and has replaced my regex with the current one.
> Fix Space Error in isSlug()

- README.md
- src/index.js
- src/lib/isTaxID.js
- test/validators.js
added a validator to  check taxid
addresses https://github.com/validatorjs/validator.js/issues/1320
> feat: added isTaxId

- .travis.yml
Adding Node v6 on the build pipeline to act as a proxy for "old" browsers.
> chore(build): add node 6 on build pipeline

- src/lib/isIdentityCard.js
- test/validators.js
> improve code coverage to 99.31%

- src/lib/isURL.js
- test/validators.js
See: https://github.com/validatorjs/validator.js/issues/1375
> fix(isUrl): add proper validation for emails

- src/lib/isBase32.js
- src/lib/isBase64.js
- test/validators.js
isBase64('') and isBase32('') now return true, which is correct behaviour according to [RFC4648](https://tools.ietf.org/html/rfc4648#section-10)
Upon regeneration of the code, there were some additional files changes, I am not sure if this is right, so I made a seperate commit.
> fix isBase64 and isBase32 seeing empty string as invalid, fixes #1418

- es/lib/normalizeEmail.js
- lib/normalizeEmail.js
- src/lib/normalizeEmail.js
- validator.js
There is a small typo in es/lib/normalizeEmail.js, lib/normalizeEmail.js, src/lib/normalizeEmail.js, validator.js.
Should read `preferred` rather than `preffered`.
> docs: Fix simple typo, preffered -> preferred

- src/lib/isEmail.js
- test/validators.js
This PR skips the special validation of the domain and user if `ignore_max_length` is set to true.  The README already implies this behavior is happening:
>  If ignore_max_length is set to true, the validator will not check for the standard max length of an email.
Closes https://github.com/validatorjs/validator.js/issues/1434
> Do not validate the length of email parts if ignore_max_length is true

- src/lib/isTaxID.js
* Prefix US-related functionality with "enUs"
* Remove assumption of global IRS-like campus prefixes
* Move US prefix check into separate function
* Add per-locale check function lookup table
* Support future locales lacking a check function (e.g. UK)
* Remove unneeded sorting of the IRS campus prefixes
* Add comments
> Refactor isTaxID for supporting more locales

- README.md
- src/index.js
- src/lib/isBase58.js
- test/validators.js
Add functionality of isBase58 based on a recommendation from @genus1 as stated in #1421.
> add isBase58 functionality

- test/client-side.js
- test/exports.js
- test/validators.js
Hi, just a quick fix. IDE was showing errors, it looks like `assert.equal()` was deprecated.
https://nodejs.org/api/assert.html#assert_assert_equal_actual_expected_message
> chore: update assert.equal() to assert.strictEqual()

- .gitignore
So in my previous pr for excluding build files, I had added `lib` to `gitgnore`, turns out doing that also removes the tracking of files under `src/lib`. This PR fixes that
> fixed lib in gitignore

- src/lib/util/assertString.js
@profnandaa I have updated the assertString utility function in src/lib/util/assertString.js.
The new function is more readable and has less nesting. It has less if/else nesting and also has a consistent error message (previously some error messages have "... received a [invalidType]" and some of them have "... received [invalidType]", now it is always "... received a [invalidType]").
I measured performances of the current function and the new function, it's a small margin but the new function is faster by 0.006 to 0.01 milliseconds on an average.
> Faster, more readable, less nested and more consistent function

- src/lib/isFQDN.js
- test/validators.js
Update `isFQDN` to allow domain names with all-underscore labels when `allow_underscores` is true. Underscore is not allowed in LDH "preferred name syntax" host names, but may appear anywhere in generic domain name labels (cf. [RFC 8499](https://tools.ietf.org/html/rfc8499#page-8)).
> fix(isFQDN): allow all-underscore labels with allow_underscores (#1253)

- CHANGELOG.md
- **New features**:
- `isVAT` [#1463](https://github.com/validatorjs/validator.js/pull/1463) @ CodingNagger
- `isTaxID` [#1446](https://github.com/validatorjs/validator.js/pull/1446) @tplessas
- `isBase58` [#1445](https://github.com/validatorjs/validator.js/pull/1445) @ezkemboi
- `isStrongPassword` [#1348](https://github.com/validatorjs/validator.js/pull/1348) @door-bell
- **Fixes and Enhancements**:
- [#1486](https://github.com/validatorjs/validator.js/pull/1486) `isISO8601`: add `strictSeparator` @brostone51
- [#1474](https://github.com/validatorjs/validator.js/pull/1474) `isFQDN`: make more strict @CristhianMotoche
- [#1469](https://github.com/validatorjs/validator.js/pull/1469) `isFQDN`: `allow_underscore` option @gibson042
- …
> release staging: Nov 2020 release notes

- src/lib/isFQDN.js
- test/validators.js
Hello
- This PR fixes #1545 #1543 and #1544 
- I refactored isFQDN a little to prevent having multiple loops and fixed the issue with numeric domain names
- I added test cases to isFQDN, isURL and isEmail to prevent having the same issue in the future
> Fix for isFQDN wth numeric domain names

- src/lib/isStrongPassword.js
adds @ as a valid symbol, also fixes #1563
> feat(isStrongPassword): add `@` as valid symbol

- README.md
- src/lib/isMACAddress.js
- test/validators.js
Fixes #1614 
This PR simplifies regexes, update the `no_colons` option name to `noSeparators`. Fixes `macAddressWithDots` regex to only allow dots as separator.
> fix(isMacAddress): improve regexes and options

- src/lib/isSlug.js
- src/lib/rtrim.js
This should be merged after #1602 
Regexes are updated in order not to change their behaviour, but only their logic. 
Fixes #1596 and fixes #1599
> fix(isSlug & rtrim): regex no longer exposed to ReDOS attacks

- test/validators.js
This PR adds other test cases for `isSlug` validator.
> test: add `isSlug` test cases

- README.md
Change Text from "Passing anything other than a string is an error." to "Passing anything other than a string will result in an error."
> rephrase sentence for grammatical correctness

- src/lib/isLicensePlate.js
- src/lib/isStrongPassword.js
In *isLicensePlate.js* the `hasOwnProperty()` function is being used probably as a requirement of *es-lint* `guard-for-in` rule. In my opinion this linter rule brings no value here and it's preventing 100% branch coverage in tests.
> chore: improving code coverage to 100% branches

- README.md
- src/lib/isLicensePlate.js
- test/validators.js
Update 2021-03-08: removing `mercosur` as per the discussion.
Adding 2 new validators for license plates:
- `pt-BR`: Brazil is in transition from legacy format to Mercosur format, with it's own format rules. This validator accepts both legacy and new formats for Brazil;
- https://pt.wikipedia.org/wiki/Placas_de_identifica%C3%A7%C3%A3o_de_ve%C3%ADculos_no_Mercosul#_Brasil
- `mercosur`: New rules for Argentina, Brazil, Paraguay, Uruguay and Venezuela (currently suspended from Mercosur but plate format still applies).
- https://en.wikipedia.org/wiki/Vehicle_registration_plates_of_the_Mercosur
> feat(isLicensePlate): adding license plate validators for 'mercosur' and 'pt-BR' locales

- src/lib/isISIN.js
- test/validators.js
i was playing around and challenged myself to optimize `isISIN`. i'm not sure it's 100% there, but it's significantly more performant that it was.
```
$ node ./util.bench.js old-version
group times: [1390.93, 1344.84, 1396.37, 1426.44, 1408.29, 1373.00, 1517.00, 1381.53, 1372.97]
average per 100000: 1401.263
standard deviation of 9 intervals: 46.406
total: gc count: 1568, gc time: 137.500
done
$ node ./util.bench.js v3
group times: [211.69, 207.08, 213.71, 213.63, 214.08, 214.64, 213.91, 212.19, 213.39]
average per 100000: 212.703
standard deviation of 9 intervals: 2.168
total: gc count: 17, gc time: 3.633
done
> isISIN optimization

- src/lib/util/typeOf.js
- test/util.js
- Added type of utility to make sure it is easy to check the type of null, object, array, date, among others.
`I.e  type of {} == 'object' and type of null == 'null'` and not that all are `object`.
- Added tests for the same, as a way to protect any changes/breaking
> Add typeof utility

- src/index.js
- src/lib/isIBAN.js
- test/exports.js
Export a list of country codes implementing IBAN
Addressing issue #1570
> feat(niceToHave): Export list of country codes that implement IBAN

- README.md
- src/lib/isBoolean.js
- test/validators.js
This PR adds a loose option to the isBoolean validator. It defaults to `false`, and in that mode, nothing changes from the current behavior. 
When set to true, the validator will also validate `yes`, `no`, and will validate boolean strings of any case. (eg: `['true', 'True', 'TRUE', 'tRuE']`)
This PR satisfies the request in this issue. https://github.com/validatorjs/validator.js/issues/1672
> feat(isBoolean) Add loose option to isBoolean validator

- build-browser.js
- package.json
Updated rollup to solve installation error
- [] README updated (where applicable)
- [] Tests written (where applicable)
> fix: npm installation error

- .github/pull_request_template.md
I made the "briefly describe what you have done in this PR" comment that many people, among which me, forget to delete.
> chore: update `pull_request_template.md`

- src/lib/isBIC.js
- src/lib/isISO31661Alpha2.js
perf(isISO31661Alpha2): use a Set along with .has instead of includes
fix(isBIC): refactor use of CountryCodes using Set's methods
Updated `isISO31661Alpha2` to use a `Set` along with `.has` to reduce complexity from O(n) to O(1) as stated [here](https://stackoverflow.com/a/55057332/8332211).
Updated `isBIC` to use Set's methods instead of Array's.
> perf(isISO31661Alpha2): use a Set along with .has instead of includes

- src/lib/isISO31661Alpha3.js
perf(isISO31661Alpha3): use a Set along with .has instead of includes
Updated isISO31661Alpha3 to use a `Set` along with `.has` to reduce complexity from O(n) to O(1) as stated [here](https://stackoverflow.com/a/55057332/8332211).
> perf(isISO31661Alpha3): use a Set along with .has instead of includes

- src/lib/isDate.js
- test/validators.js
allow users to strictly validate dates with "." as delimiter.
Closes #1709
> fix(validators): fix isdate format validation

- src/lib/isEmail.js
- test/validators.js
The gmail domain specific validator checks the length of the username part and replaces dots as they don't count against the limit. But the replace function only replaced the first dot. Fixed by using regex with g switch.
> fix(isEmail): replace all dots in gmail length validation

- src/lib/isURL.js
- test/validators.js
fix(isURL): allow URLs with column and no port
This solves the issue #1584
> fix(isURL): allow URLs with column and no port

- src/lib/isUUID.js
- test/validators.js
The issue here lies in that, where the defaulting of argument is only managed for when the value of the version is 'undefined', and for other falsy values (in my case 'null') it accepts them. There are cases where functions do trigger callbacks with null values instead of undefined, and it usually leads to unexpected outcomes. I do believe that this is the general understanding of how the function should be used, when the version argument is falsy, it should check for 'all' pattern.
The particular issue is here:
> fix(isUUID): handle of null version value

- src/lib/isURL.js
- test/validators.js
URL with an empty user are valid.
Example:
```
http://:pass@www.foobar.com/
```
This kind of URL (${protocol}://:${password}@${hostname}:${port}) can be parsed and allows to extract the password.
discussion: https://github.com/validatorjs/validator.js/issues/1681
> feat(isUrl):  urls with empty user

- src/lib/unescape.js
- test/sanitizers.js
Fixes: #1827 
If the intermediate string contains escape sequences, eg. unescaping `&amp;lt;` resulted in incorrect output `<`. Moved &amp; unescape as last operation to handle all other sequences before that.
> fix(unescape-bug): Fixed bug where intermediate string contains escaped characters

- src/lib/rtrim.js
This PR fixes a potential ReDOS in `rtrim` sanitizer. A try has been made in #1603 to fix the same vulnerability but it looks like we failed to prevent it.
The new implementation is not based on regex and is inspired by Steven Levithan's [blog post](https://blog.stevenlevithan.com/archives/faster-trim-javascript) and [trim package](https://www.npmjs.com/package/trim) implementation.
Thanks to @yetingli for discovering the vulnerability and [huntr.dev](https://huntr.dev) for reporting it
> fix(rtrim): remove regex to prevent ReDOS attack

- README.md
This PR update the `README.md` docs to include the missing `options` optional parameter on `isISO8601` validator.
> fix(docs): add missing options synthax on isISO8601 validator

- README.md
- SECURITY.md
Hello,
As discussed in #1726 , we need a security policy to allow security researchers to report to us security vulnerabilities privately.
This PR is adding a security policy and a readme badge to facilitate vulnerability reports. I added [huntr.dev ](https://huntr.dev) because we already have 2 security vulnerabilities disclosed using that platform and the experience went very well.
> Add a security policy for the repo

- src/lib/isDataURI.js
- test/validators.js
fix(isDataURI): fix dataURI mediaType format
The readAsDataURL method [MDN](https://developer.mozilla.org/en-US/docs/Web/API/FileReader/readAsDataURL) generates a dot mediaType for some file formats (.docx - application/vnd.openxmlformats-officedocument.wordprocessingml.document, . xlsx - application/vnd.openxmlformats-officedocument.spreadsheetml.sheet).
I extended the mediaType validation pattern to be compatible with readAsDataURL.
> fix(isDataURI): fix dataURI mediaType format

- src/lib/matches.js
Refs 
https://github.com/express-validator/express-validator/issues/1127
https://github.com/express-validator/express-validator/pull/1150
> fix(matches): prevent regex state from breaking following validations

- src/lib/isMagnetURI.js
- test/validators.js
BitTorrent introduced the btmh: protocol in 2020 as part of its BitTorrent v2 changes. https://blog.libtorrent.org/2020/09/bittorrent-v2/
This schema like: `magnet:?xt=urn:btmh:1220{64 hashs}`
And This pull request will let `isMagnetURI` function support vaild this schema.
I Also remove the restrict of `xt=urn:` after `magnet:?`, since [Magnet_URI_scheme](https://en.wikipedia.org/wiki/Magnet_URI_scheme) Format notice:
> Magnet URIs consist of a series of one or more parameters, **the order of which is not significant,** formatted in the same way as [query strings](https://en.wikipedia.org/wiki/Query_string) that ordinarily terminate [HTTP](https://en.wikipedia.org/wiki/HTTP) URLs.
> feat(isMagnetURI): support Bittorrent v2

- src/lib/isURL.js
- test/validators.js
> do not check if the host is valid if no host is specified and not require_host

- src/lib/isDataURI.js
- src/lib/isEmail.js
- src/lib/isIdentityCard.js
- src/lib/isTaxID.js
- src/lib/isURL.js
[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated so we replace it with [String.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) which works similarily but isn't deprecated.
.substr() probably isn't going away anytime soon but the change is trivial so it doesn't hurt to do it.
> refactor: replace deprecated String.prototype.substr()

- src/lib/isFQDN.js
- test/validators.js
According to the mentioned on this comment https://github.com/validatorjs/validator.js/issues/1923#issuecomment-1029809187
> Example: `abc.efg.g1h.` will always fail, current `options` don't provide this use case, but is valid
> 
> ```js
> validator.isFQDN('abc.efg.g1h.', 
>   { allow_trailing_dot: true, allow_underscores: true, allow_numeric_tld: true}); // false but should be true
> ```
the option allow_numeric_tld didn't work as supposed to do, this PR tries to fix that.
> fix(isFQDN): allow_numeric_tld option didn't work

- src/lib/isLength.js
- test/validators.js
#1941
- Added process to subtract presentation sequence characters from total characters
- Edited test
https://unicode.org/reports/tr51/#Emoji_Variation_Sequences
> fix(isLength): added process to subtract Presentation Sequences characters

- src/lib/isIP.js
Closes #1962
- ~~[ ] Tests written (where applicable)~~
> refactor(isIP): removed redundant check for IPv4 addresses

- README.md
> Fix broken Validators table at README.md

- README.md
Added in https://github.com/validatorjs/validator.js/pull/1678 without specific reason
> Remove 'Changes made' from README

- .github/workflows/codeql-analysis.yml
As described in #2149 
https://github.blog/changelog/2022-04-27-code-scanning-deprecation-of-codeql-action-v1/
fixes #2149
- ~~[ ] Tests written (where applicable)~~
> chore(CodeQL): update deprecated v1 to v2

- src/lib/isStrongPassword.js
- test/validators.js
Add £ to symbolRegex, for isStrongPassword.
Sorry for creating a double PR, but noticed that PR hadn't been touched in 5 days
> Validator does not recognise £ as symbol

- src/lib/isBtcAddress.js
* there is no need to do a check before, which RegExp use, just test for both and return accordingly, if either one matches
* refactored version also is bit faster as well, according to Benchmark.js tests I did
* also removed one unnecessary comment line, it does not really add any information at all
- ~~[ ] Tests written (where applicable)~~
> refactor(isBtcAddress): get rid of unnecessary if statement and comment

- CHANGELOG.md
Remove duplicated section in CHANGELOG.md, which was listed twice for some reason:
```
- [#1706](https://github.com/validatorjs/validator.js/pull/1706) `isISO4217`, currency code validator @jpaya17
```
- ~~[ ] Tests written (where applicable)~~
> docs(CHANGELOG): remove duplicated "New Features" section

- src/lib/isMimeType.js
- test/validators.test.js
Add `_` (underscore) to the `mimeTypeSimple` RegExp to fix valid MIME types not getting matched.
Kindly check #2119  for more details
This fixes #2119
> fix(isMimeType): Fix MIME Types with underscores not getting matched

- src/lib/isRgbColor.js
- test/validators.test.js
Fix validation of "rgb(a)ColorPercent" strings, see #2113 
The current RegExp is missing the "end of string" anchor, so it will also match values with additional string content after the actual rgb color part, kindly check the issue above for examples.
This fixes #2113 
> fix(isRgbColor): Fix validation of rgb(a)ColorPercentage strings

- src/lib/isEmail.js
- test/validators.test.js
> Fixes #2218 
- Excluded non-breaking space character from range of acceptable UTF8 characters in the user part of email address
- Added test cases to confirm fix
> isEmail: do not allow non-breaking space in user part

- src/lib/isJWT.js
- test/validators.test.js
This PR fixes the validation issue in the isJWT function where it was returning true for a 2-part invalid JWT token. The fix is to check for len < 3 instead of len < 2 in the code.
Changes Made:
Updated the validation check for len < 3 in isJWT function
Testing:
Ran unit tests for the isJWT function and verified that it now returns false for 2-part invalid JWT tokens.
>  Fix validation issue in isJWT function

- src/lib/isCreditCard.js
Hello,
I've refactored the way the `allCards` variable is created/handled in isCreditCard:
It currently is **manually** hardcoding all of the previously already defined RegExp into one huge RegExp, that it later then checks against.
This is problematic, because:
* it adds unnecessary code duplication (you need to store the provider RegExps in two places: 1x on its own and 1x inside `allCards`
* (at least to my eyes) it is unreadable
* therefore it makes it a nightmare to update RegExps or add new providers
I've replace it with a dynamically created array with the RegExps from the `cards` object instead, which will make it a lot easier to maintain and update, when new providers are added:
* you only need to add the RegExp inside the `cards` object
* no manual copying of the RegExp …
> refactor(isCreditCard): create allCards dynamically and get rid of hard-to-maintain hardcoded version

- package.json
- src/lib/isDate.js
- test/validators.test.js
This pull request resolves issues with false negatives when using the `isDate` validator (Issue #2256). When parsing dates, the `YYYY-MM-DD` date format gets interpreted to be in the UTC time zone ([MDN Docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse#using_date.parse)), while the `getDate()` method outputs the day of the month in the current time zone ([MDN Docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getDate)). This apples-to-oranges comparison can result in occasional discrepancies, depending on the user's local time and timezone.
This PR appends `T00:00:00` time information into the parsed string (as suggested by @brunoabude). That will cause the  date string to be interpreted in the local …
> fix(isDate): Timezone Offset Fix

- src/lib/isPassportNumber.js
- test/validators.test.js
fix(isPassportNumber): regex fix for Azerbaijan
Fixed regex for Azerbaijan isPassportNumber
https://irb.gc.ca/en/country-information/rir/Pages/index.aspx?doc=455354&pls=1
"According to Keesing, the passport number is 8 digits preceded by a letter (ibid.)"
> fix(isPassportNumber): fix regex Azerbaijan

- src/lib/isPostalCode.js
- test/validators.test.js
I have improved the regular expression for postal codes of the Netherlands. They cannot start with a zero, and they cannot contain "SA", "SD" and "SS".
More information: https://en.wikipedia.org/wiki/Postal_codes_in_the_Netherlands
> fix(isPostalCode): Improve Dutch postal code regex

- .github/workflows/npm-publish.yml
chore: Publish to NPM with provenance
The release process in this repository is already automated via GitHub Actions, which is a great first step toward creating trust in the supply chain. Recently, NPM has started to support publishing with the `--provenance` flag. This flag creates a link between the GitHub Actions run that created the release and the final artifact on NPM. This linkage further ensures that package installs can be traced back to a specific code revision.
For more information on publishing with provenance, please refer to: https://github.blog/2023-04-19-introducing-npm-package-provenance/
Note that the update of Node.js to v18 is required for NPM v9.5+ to be installed, which is needed for provenance.
> chore: Publish to NPM with provenance

- src/lib/isStrongPassword.js
- test/validators.test.js
I modified the special character regex a little bit to add validation for '\\' character. I worked on this based on an [issue](https://github.com/validatorjs/validator.js/issues/2261) in the repository
> Modified symbolRegex in isStrongPassword to include '\'

- README.md
> doc: Update README.md for installation with other package managers

- README.md
I would like to propose to add both Rik and Rubin as maintainers on the project because of their dedication to the project in the past 2+ years. They have been serving as triagers / moderators in the past period.
I will also look forward to hand over the keys to a new guard very soon -- to take the project to new heights.
Long live validator.js <3
-na
> chore: add rik and rubin as maintainers

- src/lib/isEmail.js
- test/validators.test.js
Fixes the bug #2392 
Order of blacklist characters check should be done before allow_utf8_local_part check since, that could possibly be true ignoring blacklisted characters
Added Appropriate validations tests data
> fix(isEmail): blacklist character check fix for #2392

- src/lib/isFloat.js
- src/lib/isInt.js
- src/lib/util/nullUndefinedCheck.js
- test/validators.test.js
Enhanced both the 'isInt' and 'isFloat' functions by incorporating checks for null and undefined values, enabling them to handle cases where the input may be null or undefined
https://github.com/validatorjs/validator.js/issues/2328
> fix(isInt, isFloat): Handle undefined and null values

- src/lib/isEmail.js
- test/validators.test.js
an email of the type "example*@gmail.com was accepted due to an errant if statement in isEmail.js file which was only checking for the first double quote (user[0] === '"'). Fixed it by adding a secondary "and" condition along with it, to ensure the local part is completely enclosed in the double quotes (&& user[user.length - 1] === '"').
> fixed issue #2432

- src/lib/normalizeEmail.js
- test/sanitizers.test.js
Added an option to ignore yandex domain conversion. Currently @yandex.ua is being converted to @yandex.ru. Added support to make this behaviour optional.
Refer Issue #2440
> feat(normalizeEmail): optional yandex domain conversion

- test/testFunctions.js
Hello,
the error message that the testFunctions currently throws, when a test case fails is currently not correctly displaying options objects, even though the intention clearly is there.
This pull request properly implements this now, by stringifying the arguments, making sure they can get correctly printed as string.
Before
`Error: validator.isDate("2024/05/01", [Object object]) passed but should have failed`
After:
`Error: validator.isDate("2024/05/01", {"delimiters":["/"," "],"format":"YYYY/MM/DD","strictMode":false}) passed but should have failed`
This is achieved by a tiny helper function that maps through the args and JSON.stringifys them.
All of these are available since node v0.10, so we still are compatible with that (ancient :)) version: …
> test(testFunctions): display stringified arguments in error message

- src/lib/isISO6346.js
- test/validators.test.js
feat(isISO6346): improve ISO6346 container ID validation with checksum adjustments
This PR enhances the isISO6346 validator to comply more accurately with the ISO 6346 standard, specifically addressing checksum validation for container IDs where the checksum result is 10. According to the standard, if the checksum is 10, the check digit should be represented as 0. This update improves accuracy in validating container IDs, particularly for freight containers (category 'U') where the checksum is mandatory.
- Adjusting checksum validation to handle cases where the checksum is 10, setting the check digit to 0 as per the standard.
- Adding tests for container IDs with check digits of 0 (when the checksum is 10) to ensure the validator correctly processes edge cases.
"If the final difference is …
> Assign check digit to 0 if remainder is 10

- CHANGELOG.md
- [#2399](https://github.com/validatorjs/validator.js/pull/2399) `isISO31661Numeric` @RobinvanderVliet
- [#2294](https://github.com/validatorjs/validator.js/pull/2294) `isULID` @arafatkn
- [#2215](https://github.com/validatorjs/validator.js/pull/2215) `isISO15924` @xDivisionByZerox
- `isMobilePhone`
- [#2395](https://github.com/validatorjs/validator.js/pull/2395) add `es-GT` locale @ignaciosuarezquilis
- [#1971](https://github.com/validatorjs/validator.js/pull/1971) improve `en-GB` locale @ihmpavel
- [#2359](https://github.com/validatorjs/validator.js/pull/2359) improve `uk-UA` locale @arttiger
- [#2350](https://github.com/validatorjs/validator.js/pull/2350) improve `ky-KG` locale @sadraliev
- [#2482](https://github.com/validatorjs/validator.js/pull/2482) improve `en-ZM` locale …
> maintenance: 2503 release

- README.md
- src/lib/isBase64.js
- test/validators.test.js
- test/validators/isBase64.test.js
Add padding to the options list.
Update regexes to support validation with and without padding.
Update default options to maintain backward compatibility.
Add new tests to cover various scenarios.
In the previous version, only Base64 strings with padding and URL-safe Base64 strings without padding were validated. However, according to [RFC4648](https://datatracker.ietf.org/doc/html/rfc4648), both standard and URL-safe Base64 variants can be valid with or without padding. Therefore, this version supports four validation combinations—standard with padding, standard without padding, URL-safe with padding, and URL-safe without padding—while maintaining backward compatibility.
> feat(isBase64): improve base64 validation based on RFC4648

- src/lib/util/assertString.js
- test/util.test.js
@profnandaa, 
I have a possible improvement for the assertString.
I am reducing the number of necessary validations and also a more assertive approach, in my point of view (if this approach doesn't make sense, I would appreciate feedback on it, if possible).
The performance has also improved, it wasn't something incredible, but it was considerable.
Unit tests:
> Refactor assertString: Faster, less nested and more consistent.

- CHANGELOG.md
- package.json
- src/index.js
- `isMobilePhone`
- [#2514](https://github.com/validatorjs/validator.js/pull/2514) improve `el-CY` locale @rezk2ll
- [#2512](https://github.com/validatorjs/validator.js/pull/2512) improve `pt-AO` locale @renaldodev
- [#2502](https://github.com/validatorjs/validator.js/pull/2502) improve `ar-OM` locale @tomcastro
- [#2089](https://github.com/validatorjs/validator.js/pull/2089) `isIP`: allow usage of option object @pixelbucket-dev
- [#2526](https://github.com/validatorjs/validator.js/pull/2526) `isPassportNumber`: improve `CA` locale @evanbechtol
- [#2491](https://github.com/validatorjs/validator.js/pull/2491) `isBase64`: improve validation based on RFC4648 @aseyfpour
- [#2479](https://github.com/validatorjs/validator.js/pull/2479) `isPostalCode`: improve `FR` locale @Rajput-Balram
- …
> maintenance: 2505 release

- test/validators.test.js
Use `locale:` instead of `local:` for isPhoneNumber test.
> test: Fix typo in validators.test.js
